name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main   # deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies and package Lambda
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package/
          cp *.py package/
          cd package && zip -r ../lambda.zip .



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # change this to your region

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name cxmt-event-2025-10 \
            --zip-file fileb://lambda.zip
